# Generated by Django 6.0.1 on 2026-01-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='disponibilidade',
            field=models.TextField(blank=True, help_text='Ex: Seg a Sex, 08h as 18h', null=True),
        ),
    ]
