# Generated by Django 6.0.2 on 2026-07-19 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_arquivoclinico_acessoarquivoclinico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('WHATSAPP', 'Whatsapp'), ('EMAIL', 'Email'), ('SMS', 'Sms'), ('PUSH', 'Push'), ('INTERNO', 'Interno')], max_length=12)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('ENVIADA', 'Enviada'), ('ERRO', 'Erro'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15)),
                ('erro', models.TextField(blank=True)),
                ('agendada_para', models.DateTimeField()),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='api.agendamento')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='api.clinica')),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='api.orcamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agendada_para', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criacao'), ('CANCELAMENTO', 'Cancelamento'), ('CONFIRMACAO', 'Confirmacao'), ('TENTATIVA_ENVIO', 'Tentativa_Envio'), ('ERRO_ENVIO', 'Erro_Envio')], max_length=20)),
                ('detalhes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_notificacao', to=settings.AUTH_USER_MODEL)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='api.notificacao')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaComunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceita_whatsapp', models.BooleanField(default=True)),
                ('aceita_email', models.BooleanField(default=True)),
                ('aceita_sms', models.BooleanField(default=False)),
                ('aceita_push', models.BooleanField(default=False)),
                ('aceita_marketing', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_comunicacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.SlugField(max_length=100)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'Whatsapp'), ('EMAIL', 'Email'), ('SMS', 'Sms'), ('PUSH', 'Push'), ('INTERNO', 'Interno')], max_length=12)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('corpo', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates_mensagem', to='api.clinica')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_mensagem_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo', '-versao'],
            },
        ),
        migrations.AddField(
            model_name='notificacao',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='api.templatemensagem'),
        ),
        migrations.AddConstraint(
            model_name='templatemensagem',
            constraint=models.UniqueConstraint(fields=('codigo', 'versao'), name='template_codigo_versao_unico'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['clinica', 'paciente', 'status', 'agendada_para'], name='api_notific_clinica_f0d3ac_idx'),
        ),
    ]
