# Generated by Django 6.0.2 on 2026-07-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_notificacao_eventonotificacao_preferenciacomunicacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferenciacomunicacao',
            options={'ordering': ['paciente_id']},
        ),
    ]
